owner: dilushanka
repo: status

sites:
  - name: REDFIX
    url: https://redfix.lk
  - name: Sitemap
    url: https://redfix.lk/sitemap_index.xml

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: REDFIX Status
  introTitle: "**REDFIX** Service Status"
  introMessage: Real-time monitoring of [redfix.lk](https://redfix.lk).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dilushanka/status
